version: "3.9"

services:
  sharelatex:
    image: sharelatex/sharelatex:latest
    container_name: sharelatex
    restart: always
    ports:
      - "0.0.0.0:80:80" # 监听 IP 与端口，可自行修改
    environment:
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex # Mongo 连接地址，可修改
      OVERLEAF_REDIS_HOST: redis # Redis 主机名，可修改
      REDIS_PORT: 6379 # Redis 端口，可修改
      GIT_BRIDGE_ENABLED: false # 如需启用 Git Bridge，请改为 true
      GIT_BRIDGE_HOST: git-bridge
      GIT_BRIDGE_PORT: 8000
      V1_HISTORY_URL: http://sharelatex:3100/api
      OVERLEAF_SECURE_COOKIE: "true"
      OVERLEAF_TRUSTED_PROXY_IPS: loopback,172.16.0.0/12 # 可信代理 IP，可修改
      OVERLEAF_BEHIND_PROXY: "true"
    volumes:
      - ./data/sharelatex:/var/lib/overleaf # 数据存储路径，可修改
      - ./data/logs:/var/log/overleaf # 日志路径，可修改
      # 如需使用 sibling containers，请取消下行注释
      # - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./config/variables.env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
      git-bridge:
        condition: service_started
      nginx:
        condition: service_started
    links:
      - mongo
      - redis
      - git-bridge
    stop_grace_period: 60s

  mongo:
    image: mongo:4.0 # Mongo 镜像，可修改
    container_name: mongo
    restart: always
    command: --replSet overleaf # 启动参数，可修改
    volumes:
      - ./data/mongo:/data/db # 数据目录，可修改
    expose:
      - 27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:5.0 # Redis 镜像，可修改
    container_name: redis
    restart: always
    command: --appendonly yes # 启动参数，可修改
    volumes:
      - ./data/redis:/data # 数据目录，可修改
    expose:
      - 6379

  git-bridge:
    image: overleaf/git-bridge:latest # Git Bridge 镜像，可修改
    container_name: git-bridge
    restart: always
    volumes:
      - ./data/git-bridge:/data/git-bridge # 数据目录，可修改
    environment:
      GIT_BRIDGE_API_BASE_URL: http://sharelatex:3000/api/v0/ # API 地址，可修改
      GIT_BRIDGE_OAUTH2_SERVER: http://sharelatex
      GIT_BRIDGE_POSTBACK_BASE_URL: http://git-bridge:8000
      GIT_BRIDGE_ROOT_DIR: /data/git-bridge
      LOG_LEVEL: INFO # 日志级别，可修改
    env_file:
      - ./config/variables.env
    expose:
      - 8000

  nginx:
    image: nginx:1.28-alpine # Nginx 镜像，可修改
    container_name: nginx
    restart: always
    ports:
      - "0.0.0.0:443:443" # TLS 监听 IP 与端口，可修改
      - "127.0.1.1:80:80" # HTTP 监听 IP 与端口，可修改
    volumes:
      - ./certs/nginx_key.pem:/certs/nginx_key.pem:ro # TLS 私钥路径，可修改
      - ./certs/nginx_certificate.pem:/certs/nginx_certificate.pem:ro # TLS 证书路径，可修改
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Nginx 配置文件路径，可修改
